package by.it.machuga.jd02_02.util;

public class Constants {
    public static final String CUSTOMER = "Customer ";
    public static final String GOOD = "Good ";
    public static final String PENSIONER = "Pensioner ";
    public static final String GOODS = "Goods=";
    public static final String STORE = "Store ";
    public static final String STUDENT = "Student ";
    public static final String NEW_LINE = "\n";
    public static final String ITEM = "Item: ";
    public static final String PRICE = " -> price: ";
    public static final String SHOP_NAME = "Spar";
    public static final String STARTED_CHOOSE_GOODS_MSG = "%s started to choose goods%n";
    public static final String FINISHED_CHOOSE_GOODS_MSG = "%s finished to choose goods%n";
    public static final String ENTERED_STORE_MSG = "%s entered the store%n";
    public static final String CHOSEN_GOOD_MSG = "%s has chosen %s%n";
    public static final String LEFT_STORE_MSG = "%s left the store%n";
    public static final String STORE_OPENED_MSG = "%s opened%n";
    public static final String STORE_CLOSED_MSG = "%s closed%n";
    public static final int MIN_SELECTION_SPEED = 100;
    public static final int MAX_SELECTION_SPEED = 300;
    public static final int MAX_STORE_OPENED_MINUTES = 2;
    public static final int FIRST_SECOND = 1;
    public static final int LAST_SECOND = 60;
    public static final int MIDDLE_SECOND = 30;
    public static final int MIN_QUANTITY = 10;
    public static final int MAX_QUANTITY = 40;
    public static final int MAX_SERVICE_TIMEOUT = 5000;
    public static final int MIN_SERVICE_TIMEOUT = 2000;
    public static final int TIMEOUT = 1000;
    public static final int CUSTOMER_NAME_LENGTH = 5;
    public static final int MIN_PRICE_LIST_SIZE = 10;
    public static final int MAX_PRICE_LIST_SIZE = 100;
    public static final int GOOD_NAME_LENGTH = 4;
    public static final double MIN_PRICE = 0.1;
    public static final int MAX_PRICE = 100;
    public static final String CASHIER_OPENED_MSG = "%s opened%n";
    public static final String CASHIER_CLOSED_MSG = "%s closed%n";
    public static final String GOES_TO_QUEUE_MSG = "%s goes to the queue%n";
    public static final String LEFT_QUEUE_MSG = "%s left the queue%n";
    public static final int PLAN_QUANTITY_CUSTOMER = 100;
    static final String ALPHABET_UPPERCASE = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    static final String ALPHABET_LOWERCASE = "abcdefghijklmnopqrstuvwxyz";
}
